### ISSUE TITLE
CellML comparison treating exponents strangely

### ISSUE THREAD

**Issue by mirams** [binfalse/BiVeS-CellML#3]
Hi Martin, 

I think this is a bug report! 
I've been enjoying BiVeS via the Rostock API, noticed a quirky problem here:
https://scrambler.cs.ox.ac.uk/entities/models/compare/38:2a634280b8ddfa3d9b16b396af548b07858af34d/38:5f73f1453ecaf645421548331dac225daa97cbab/show/priebe_beuckelmann_1998.cellml/displayBivesDiff

![image](https://user-images.githubusercontent.com/858776/99956860-a9a19400-2d7e-11eb-998f-9fbeb270a584.png)

There are no changes to the maths in this part of the model, but you'll see it is treating what were the exponents as new variables, this is because we edited the file in a recent version of OpenCOR and it is now writing exponents (powers of 10) like this:
`<cn cellml:units="per_ms" type="e-notation">3.013<sep/>-3</cn>` 
(BiVeS doesn't like this version, although it's the offically recognised way of doing it in CellML I think)
whereas in the old version it’s doing
`<cn cellml:units="per_ms">3.013e-3</cn>`
(BiVeS is fine with this)

**Comment by binfalse** [comment]
Hi Gary, nice to hear from you :)
Indeed, that looks like a bug! I will have a look into it

**Comment by mirams** [comment]
Great - thanks!

**Comment by binfalse** [comment]
That's *just* been an issue with printing the math part of the document.

Past-martin apparently assumed that an XML node, which contains text content, can only have a single child.. But current-martin is smarter, and future-martin will try to avoid such stupid assumptions ;-)

The new libraries are already deployed to ossrh, however it will take some time until they appear at maven central. The docker image for the web application will then be rebuilt and a fresh container will be deployed to our servers. You'll thus get the fix automatically. At some point ;-)

I'll check tomorrow if the link above is working.

Cheers,
Martin

**Comment by binfalse** [comment]
Just checked the link and it seems to be ok now..?

It may be a bit confusing that `3.013e-3` was replaced by `3.013 e -3` (the spacing around the `e` is pretty small when rendered)...? I guess that change also has no real effect on the simulation. Anyway, there is a change and I cannot really weight its impact and I think it makes sense to highlight it, to draw the user's attention to the change, so (s)he can investigate the differences manually.

I'll close here, let me know if it still doesn't work for you!

**Comment by mirams** [comment]
Hi, that is fast, great thank you. 

Those are really completely mathematically equivalent, so I think everyone would be happy not showing any changes for these and treating those numbers as identical (if people are worried about exactly how the model is serialised to CellML I think they would be looking at the CellML diff anyway - the great thing about BiVeS is not having to see and worry about those details!).
